# Generated by Django 4.0.7 on 2024-01-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_edited_comment_edited_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='edited_body',
        ),
    ]
